// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onTriggerLevelChange();

float current_Humid;
float current_Temperature;
int current_Moisture;
int raw_Moisture;
int trigger_Level;
bool pump_Status;

void initProperties(){

  ArduinoCloud.addProperty(current_Humid, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(current_Temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(current_Moisture, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(raw_Moisture, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(trigger_Level, READWRITE, ON_CHANGE, onTriggerLevelChange);
  ArduinoCloud.addProperty(pump_Status, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
