/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/530e87a0-3767-4288-9aad-ea5f14107c6a

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float current_Humid;
  float current_Temperature;
  int current_Moisture;
  int raw_Moisture;
  int trigger_Level;
  bool pump_Status;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "Arduino.h"

// moisture sensor calliberation
int sensor_Raw;

#define SENSOR_IN 0
#define SENSOR_DRY 3330
#define SENSOR_WET 2400


// DHT sensor library - Version: Latest
#include <DHT.h>
#include <DHT_U.h>

#define DHTPIN 8
#define DHTTYPE DHT11

DHT dht(DHTPIN, DHTTYPE);

// <Water pump>
// define pins for signal output
#define motorPin1 6
#define motorPin2 5
// setting local pump trigger
int pump_trigger = 30;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();
  
  // set ADC to read 12 bits
  analogReadResolution(12);

  dht.begin();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);


  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  // configuring the pins for the motor driver
  pinMode(motorPin1, OUTPUT);
  pinMode(motorPin2, OUTPUT);
  // Initialising to off: pump off
  digitalWrite(motorPin1, LOW);
  digitalWrite(motorPin2, LOW);
  // Initialising pump status to off
  pump_Status = false;
  
}

void loop() {
  ArduinoCloud.update();
  
  // <SOIL MOISTURE SENSOR>
  // reading raw moisture value
  sensor_Raw = analogRead(SENSOR_IN);
  // passing value to raw moisture cloud variable
  raw_Moisture = sensor_Raw;
  // mapping value as a percent with calliberated values
  int moisture_percent = map(sensor_Raw, SENSOR_DRY, SENSOR_WET, 0, 100);
  moisture_percent = constrain(moisture_percent, 0, 100);
  // passing value to cloud variable
  current_Moisture = moisture_percent;
  
  // <DHT MODULE>
  // read temperature and humidity values
  int temperature = dht.readTemperature();
  int humidity = dht.readHumidity();
  // passing values to cloud variables
  current_Temperature = temperature;
  current_Humid = humidity;
  
  // <PUMP TRIGGER>
  if (moisture_percent <= pump_trigger){
    pumpOn();
  } else {
    pumpOff();
  }

  //digitalWrite(motorPin1, LOW);
  //digitalWrite(motorPin2, LOW);
}


void pumpOn(){
  digitalWrite(motorPin1, LOW);
  digitalWrite(motorPin2, HIGH);
  pump_Status = true;
}

void pumpOff(){
  digitalWrite(motorPin1, LOW);
  digitalWrite(motorPin2, LOW);
  pump_Status = false;
}





/*
  Since TriggerLevel is READ_WRITE variable, onTriggerLevelChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTriggerLevelChange()  {
  // set pump trigger to trigger_level value received from cloud
  pump_trigger = trigger_Level;
}
